[build]
  publish = "build"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  # Disable caching to ensure function updates deploy immediately
  included_files = ["netlify/functions/**"]

# Disable function caching for faster updates
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
